-- Généré par tools/gen_answers_lua.py — ne pas éditer à la main.
return {
	remplacements = {
		["Locations/Acropolis/follower.gdc"] = {
			{"var is_correct: bool = answer.to_lower() in $MemorialScreen / CenterContainer / VBoxContainer / Answer1.text.to_lower()", "var is_correct: bool = answer.to_lower() in $MemorialScreen / CenterContainer / VBoxContainer / Answer1.text.to_lower() or _fr_alias(answer, $MemorialScreen / CenterContainer / VBoxContainer / Answer1.text.to_lower())"},
		},
		["Locations/Constellation/power_terminal.gdc"] = {
			{"if text.to_lower() == \"immortal\":", "if text.to_lower() in [\"immortal\", \"immortalite\", \"immortalité\", \"immortel\", \"immortelle\"]:"},
		},
		["Locations/Deep Flux Lab/entrance_terminal.gdc"] = {
			{"if \"tablet\" in text.to_lower() or text.to_lower() in [\"tablet\", \"the tablet\"]:", "if \"tablet\" in text.to_lower() or \"la tablette\" in text.to_lower() or \"tablette\" in text.to_lower() or text.to_lower() in [\"tablet\", \"the tablet\"]:"},
		},
		["Locations/Hall of Forms/table.gdc"] = {
			{"if answer in text.to_lower():", "if answer in text.to_lower() or _fr_alias(answer, text.to_lower()):"},
		},
		["Locations/Hall of Judgment/crimes_list.gdc"] = {
			{"var crime_4_answers: Array[String] = [\"sferdan\", \"mandal\", \"costeau\", \"archive curators\"]", "var crime_4_answers: Array[String] = [\"sferdan\", \"mandal\", \"costeau\", \"archive curators\", \"conservateurs d'archives\", \"les conservateurs d'archives\", \"archivistes\", \"les archivistes\"]"},
		},
		["Locations/Hypercube/door_seal.gdc"] = {
			{"if text.to_lower() in [\"1034\", \"10 3 4\", \"1 0 3 4\", \"ten three four\", \"ten thousand thirty four\"]:", "if text.to_lower() in [\"1034\", \"10 3 4\", \"1 0 3 4\", \"ten three four\", \"ten thousand thirty four\", \"dix trois quatre\", \"mille trente quatre\", \"mille trente-quatre\"]:"},
		},
		["Locations/Memorial to the Lost/grave_seal.gdc"] = {
			{"if text.to_lower() == \"elysium\":", "if text.to_lower() in [\"elysium\", \"élysium\"]:"},
		},
		["Locations/Parallel Exhibition/floor_tile.gdc"] = {
			{"if text.to_lower() in answers:", "if _fr_accepte(answers, text.to_lower()):"},
		},
		["Locations/Station X/bio_terminal.gdc"] = {
			{"if text.to_lower() == \"elysium\":", "if text.to_lower() in [\"elysium\", \"élysium\"]:"},
		},
		["Locations/Superserver/super_terminal.gdc"] = {
			{"if answer.to_lower() in text.to_lower():", "if answer.to_lower() in text.to_lower() or _fr_alias(answer, text.to_lower()):"},
		},
		["Locations/Tower of Languages/tower_block.gdc"] = {
			{"if answer in text.to_lower():", "if answer in text.to_lower() or _fr_alias(answer, text.to_lower()):"},
		},
		["Scenes/Entities/cuffs.gdc"] = {
			{"\tif name_answer.to_lower() in name_text.to_lower() and title_text.to_lower() == title_answer.to_lower():", "\tif (name_answer.to_lower() in name_text.to_lower() or _fr_alias(name_answer, name_text.to_lower())) and (title_text.to_lower() == title_answer.to_lower() or _fr_alias(title_answer, title_text.to_lower())):"},
		},
		["Scripts/passage.gdc"] = {
			{"\t\t\t$RichTextLabel.text = decrypt(text, key)", "\t\t\tvar clair := decrypt(text, key)\n\t\t\tvar traduction: String = FR_CLAIRS.get(clair, \"\")\n\t\t\tif traduction.is_empty():\n\t\t\t\t$RichTextLabel.text = clair\n\t\t\telse:\n\t\t\t\t$RichTextLabel.text = clair + \"\\n\\n\" + traduction"},
		},
		["Scripts/terminal_manager.gdc"] = {
			{"\t\t\"download\":", "\t\t\"download\", \"telecharger\", \"télécharger\":"},
			{"\t\t\"unlock\":", "\t\t\"unlock\", \"deverrouiller\", \"déverrouiller\":"},
			{"\t\t\"help\":", "\t\t\"help\", \"aide\":"},
			{"\t\t\"lock\":", "\t\t\"lock\", \"verrouiller\":"},
			{"\t\t\"key\":", "\t\t\"key\", \"cle\", \"clé\":"},
		},
	},
	aides = {
		["Locations/Acropolis/follower.gdc"] = "\n\nconst FR_ALIASES := {\n\t\"announcer\": [\"annonciateur\", \"crieur\", \"heraut\", \"héraut\"],\n\t\"biibiyt\": [\"djjmsvl\"],\n\t\"core\": [\"coeur\", \"cœur\", \"noyau\"],\n\t\"elysium\": [\"élysium\"],\n\t\"false\": [\"f\", \"faux\"],\n\t\"flow\": [\"courant\", \"flot\", \"le flot\"],\n\t\"fly\": [\"envol\", \"vol\", \"voler\"],\n\t\"fool\": [\"fou\", \"idiot\", \"insense\", \"insensé\", \"le fou\"],\n\t\"herald\": [\"heraut\", \"héraut\", \"le heraut\", \"le héraut\"],\n\t\"immortal\": [\"immortalite\", \"immortalité\", \"immortel\", \"immortelle\"],\n\t\"judge\": [\"juge\", \"le juge\"],\n\t\"mad\": [\"dement\", \"dément\", \"fou\", \"le fou\"],\n\t\"no\": [\"non\"],\n\t\"novice\": [\"le novice\", \"novice\"],\n\t\"oblivion\": [\"l'oubli\", \"oubli\"],\n\t\"pattern\": [\"le motif\", \"motif\", \"motifs\", \"schema\", \"schéma\"],\n\t\"patterns\": [\"motif\", \"motifs\", \"regularites\", \"régularités\", \"schemas\", \"schémas\"],\n\t\"planetarium\": [\"planetarium\", \"planétarium\"],\n\t\"star study\": [\"etude des etoiles\", \"observatoire stellaire\", \"étude des étoiles\"],\n\t\"tablet\": [\"la tablette\", \"tablette\"],\n\t\"ten thousand thirty four\": [\"mille trente quatre\", \"mille trente-quatre\"],\n\t\"ten three four\": [\"dix trois quatre\"],\n\t\"thing\": [\"chose\", \"la chose\"],\n\t\"time\": [\"le temps\", \"temps\"],\n\t\"trickster\": [\"farceur\", \"filou\", \"fripon\"],\n\t\"true\": [\"v\", \"vrai\"],\n\t\"unintelligible\": [\"incomprehensible\", \"incompréhensible\", \"inintelligible\", \"intraduisible\", \"traduction impossible\"],\n\t\"universal mirror\": [\"miroir universel\"],\n\t\"witness\": [\"le temoin\", \"le témoin\", \"temoin\", \"témoin\"],\n\t\"world\": [\"le monde\", \"monde\"],\n\t\"y\": [\"o\"],\n\t\"yes\": [\"o\", \"oui\"],\n}\n\n\nfunc _fr_alias(reponse: String, saisie: String) -> bool:\n\tfor alias in FR_ALIASES.get(reponse.to_lower(), []):\n\t\tif alias in saisie:\n\t\t\treturn true\n\treturn false\n\n\nfunc _fr_accepte(reponses: Array, saisie: String) -> bool:\n\tif saisie in reponses:\n\t\treturn true\n\tfor reponse in reponses:\n\t\tif saisie in FR_ALIASES.get(String(reponse).to_lower(), []):\n\t\t\treturn true\n\treturn false\n",
		["Locations/Hall of Forms/table.gdc"] = "\n\nconst FR_ALIASES := {\n\t\"announcer\": [\"annonciateur\", \"crieur\", \"heraut\", \"héraut\"],\n\t\"biibiyt\": [\"djjmsvl\"],\n\t\"core\": [\"coeur\", \"cœur\", \"noyau\"],\n\t\"elysium\": [\"élysium\"],\n\t\"false\": [\"f\", \"faux\"],\n\t\"flow\": [\"courant\", \"flot\", \"le flot\"],\n\t\"fly\": [\"envol\", \"vol\", \"voler\"],\n\t\"fool\": [\"fou\", \"idiot\", \"insense\", \"insensé\", \"le fou\"],\n\t\"herald\": [\"heraut\", \"héraut\", \"le heraut\", \"le héraut\"],\n\t\"immortal\": [\"immortalite\", \"immortalité\", \"immortel\", \"immortelle\"],\n\t\"judge\": [\"juge\", \"le juge\"],\n\t\"mad\": [\"dement\", \"dément\", \"fou\", \"le fou\"],\n\t\"no\": [\"non\"],\n\t\"novice\": [\"le novice\", \"novice\"],\n\t\"oblivion\": [\"l'oubli\", \"oubli\"],\n\t\"pattern\": [\"le motif\", \"motif\", \"motifs\", \"schema\", \"schéma\"],\n\t\"patterns\": [\"motif\", \"motifs\", \"regularites\", \"régularités\", \"schemas\", \"schémas\"],\n\t\"planetarium\": [\"planetarium\", \"planétarium\"],\n\t\"star study\": [\"etude des etoiles\", \"observatoire stellaire\", \"étude des étoiles\"],\n\t\"tablet\": [\"la tablette\", \"tablette\"],\n\t\"ten thousand thirty four\": [\"mille trente quatre\", \"mille trente-quatre\"],\n\t\"ten three four\": [\"dix trois quatre\"],\n\t\"thing\": [\"chose\", \"la chose\"],\n\t\"time\": [\"le temps\", \"temps\"],\n\t\"trickster\": [\"farceur\", \"filou\", \"fripon\"],\n\t\"true\": [\"v\", \"vrai\"],\n\t\"unintelligible\": [\"incomprehensible\", \"incompréhensible\", \"inintelligible\", \"intraduisible\", \"traduction impossible\"],\n\t\"universal mirror\": [\"miroir universel\"],\n\t\"witness\": [\"le temoin\", \"le témoin\", \"temoin\", \"témoin\"],\n\t\"world\": [\"le monde\", \"monde\"],\n\t\"y\": [\"o\"],\n\t\"yes\": [\"o\", \"oui\"],\n}\n\n\nfunc _fr_alias(reponse: String, saisie: String) -> bool:\n\tfor alias in FR_ALIASES.get(reponse.to_lower(), []):\n\t\tif alias in saisie:\n\t\t\treturn true\n\treturn false\n\n\nfunc _fr_accepte(reponses: Array, saisie: String) -> bool:\n\tif saisie in reponses:\n\t\treturn true\n\tfor reponse in reponses:\n\t\tif saisie in FR_ALIASES.get(String(reponse).to_lower(), []):\n\t\t\treturn true\n\treturn false\n",
		["Locations/Parallel Exhibition/floor_tile.gdc"] = "\n\nconst FR_ALIASES := {\n\t\"announcer\": [\"annonciateur\", \"crieur\", \"heraut\", \"héraut\"],\n\t\"biibiyt\": [\"djjmsvl\"],\n\t\"core\": [\"coeur\", \"cœur\", \"noyau\"],\n\t\"elysium\": [\"élysium\"],\n\t\"false\": [\"f\", \"faux\"],\n\t\"flow\": [\"courant\", \"flot\", \"le flot\"],\n\t\"fly\": [\"envol\", \"vol\", \"voler\"],\n\t\"fool\": [\"fou\", \"idiot\", \"insense\", \"insensé\", \"le fou\"],\n\t\"herald\": [\"heraut\", \"héraut\", \"le heraut\", \"le héraut\"],\n\t\"immortal\": [\"immortalite\", \"immortalité\", \"immortel\", \"immortelle\"],\n\t\"judge\": [\"juge\", \"le juge\"],\n\t\"mad\": [\"dement\", \"dément\", \"fou\", \"le fou\"],\n\t\"no\": [\"non\"],\n\t\"novice\": [\"le novice\", \"novice\"],\n\t\"oblivion\": [\"l'oubli\", \"oubli\"],\n\t\"pattern\": [\"le motif\", \"motif\", \"motifs\", \"schema\", \"schéma\"],\n\t\"patterns\": [\"motif\", \"motifs\", \"regularites\", \"régularités\", \"schemas\", \"schémas\"],\n\t\"planetarium\": [\"planetarium\", \"planétarium\"],\n\t\"star study\": [\"etude des etoiles\", \"observatoire stellaire\", \"étude des étoiles\"],\n\t\"tablet\": [\"la tablette\", \"tablette\"],\n\t\"ten thousand thirty four\": [\"mille trente quatre\", \"mille trente-quatre\"],\n\t\"ten three four\": [\"dix trois quatre\"],\n\t\"thing\": [\"chose\", \"la chose\"],\n\t\"time\": [\"le temps\", \"temps\"],\n\t\"trickster\": [\"farceur\", \"filou\", \"fripon\"],\n\t\"true\": [\"v\", \"vrai\"],\n\t\"unintelligible\": [\"incomprehensible\", \"incompréhensible\", \"inintelligible\", \"intraduisible\", \"traduction impossible\"],\n\t\"universal mirror\": [\"miroir universel\"],\n\t\"witness\": [\"le temoin\", \"le témoin\", \"temoin\", \"témoin\"],\n\t\"world\": [\"le monde\", \"monde\"],\n\t\"y\": [\"o\"],\n\t\"yes\": [\"o\", \"oui\"],\n}\n\n\nfunc _fr_alias(reponse: String, saisie: String) -> bool:\n\tfor alias in FR_ALIASES.get(reponse.to_lower(), []):\n\t\tif alias in saisie:\n\t\t\treturn true\n\treturn false\n\n\nfunc _fr_accepte(reponses: Array, saisie: String) -> bool:\n\tif saisie in reponses:\n\t\treturn true\n\tfor reponse in reponses:\n\t\tif saisie in FR_ALIASES.get(String(reponse).to_lower(), []):\n\t\t\treturn true\n\treturn false\n",
		["Locations/Superserver/super_terminal.gdc"] = "\n\nconst FR_ALIASES := {\n\t\"announcer\": [\"annonciateur\", \"crieur\", \"heraut\", \"héraut\"],\n\t\"biibiyt\": [\"djjmsvl\"],\n\t\"core\": [\"coeur\", \"cœur\", \"noyau\"],\n\t\"elysium\": [\"élysium\"],\n\t\"false\": [\"f\", \"faux\"],\n\t\"flow\": [\"courant\", \"flot\", \"le flot\"],\n\t\"fly\": [\"envol\", \"vol\", \"voler\"],\n\t\"fool\": [\"fou\", \"idiot\", \"insense\", \"insensé\", \"le fou\"],\n\t\"herald\": [\"heraut\", \"héraut\", \"le heraut\", \"le héraut\"],\n\t\"immortal\": [\"immortalite\", \"immortalité\", \"immortel\", \"immortelle\"],\n\t\"judge\": [\"juge\", \"le juge\"],\n\t\"mad\": [\"dement\", \"dément\", \"fou\", \"le fou\"],\n\t\"no\": [\"non\"],\n\t\"novice\": [\"le novice\", \"novice\"],\n\t\"oblivion\": [\"l'oubli\", \"oubli\"],\n\t\"pattern\": [\"le motif\", \"motif\", \"motifs\", \"schema\", \"schéma\"],\n\t\"patterns\": [\"motif\", \"motifs\", \"regularites\", \"régularités\", \"schemas\", \"schémas\"],\n\t\"planetarium\": [\"planetarium\", \"planétarium\"],\n\t\"star study\": [\"etude des etoiles\", \"observatoire stellaire\", \"étude des étoiles\"],\n\t\"tablet\": [\"la tablette\", \"tablette\"],\n\t\"ten thousand thirty four\": [\"mille trente quatre\", \"mille trente-quatre\"],\n\t\"ten three four\": [\"dix trois quatre\"],\n\t\"thing\": [\"chose\", \"la chose\"],\n\t\"time\": [\"le temps\", \"temps\"],\n\t\"trickster\": [\"farceur\", \"filou\", \"fripon\"],\n\t\"true\": [\"v\", \"vrai\"],\n\t\"unintelligible\": [\"incomprehensible\", \"incompréhensible\", \"inintelligible\", \"intraduisible\", \"traduction impossible\"],\n\t\"universal mirror\": [\"miroir universel\"],\n\t\"witness\": [\"le temoin\", \"le témoin\", \"temoin\", \"témoin\"],\n\t\"world\": [\"le monde\", \"monde\"],\n\t\"y\": [\"o\"],\n\t\"yes\": [\"o\", \"oui\"],\n}\n\n\nfunc _fr_alias(reponse: String, saisie: String) -> bool:\n\tfor alias in FR_ALIASES.get(reponse.to_lower(), []):\n\t\tif alias in saisie:\n\t\t\treturn true\n\treturn false\n\n\nfunc _fr_accepte(reponses: Array, saisie: String) -> bool:\n\tif saisie in reponses:\n\t\treturn true\n\tfor reponse in reponses:\n\t\tif saisie in FR_ALIASES.get(String(reponse).to_lower(), []):\n\t\t\treturn true\n\treturn false\n",
		["Locations/Tower of Languages/tower_block.gdc"] = "\n\nconst FR_ALIASES := {\n\t\"announcer\": [\"annonciateur\", \"crieur\", \"heraut\", \"héraut\"],\n\t\"biibiyt\": [\"djjmsvl\"],\n\t\"core\": [\"coeur\", \"cœur\", \"noyau\"],\n\t\"elysium\": [\"élysium\"],\n\t\"false\": [\"f\", \"faux\"],\n\t\"flow\": [\"courant\", \"flot\", \"le flot\"],\n\t\"fly\": [\"envol\", \"vol\", \"voler\"],\n\t\"fool\": [\"fou\", \"idiot\", \"insense\", \"insensé\", \"le fou\"],\n\t\"herald\": [\"heraut\", \"héraut\", \"le heraut\", \"le héraut\"],\n\t\"immortal\": [\"immortalite\", \"immortalité\", \"immortel\", \"immortelle\"],\n\t\"judge\": [\"juge\", \"le juge\"],\n\t\"mad\": [\"dement\", \"dément\", \"fou\", \"le fou\"],\n\t\"no\": [\"non\"],\n\t\"novice\": [\"le novice\", \"novice\"],\n\t\"oblivion\": [\"l'oubli\", \"oubli\"],\n\t\"pattern\": [\"le motif\", \"motif\", \"motifs\", \"schema\", \"schéma\"],\n\t\"patterns\": [\"motif\", \"motifs\", \"regularites\", \"régularités\", \"schemas\", \"schémas\"],\n\t\"planetarium\": [\"planetarium\", \"planétarium\"],\n\t\"star study\": [\"etude des etoiles\", \"observatoire stellaire\", \"étude des étoiles\"],\n\t\"tablet\": [\"la tablette\", \"tablette\"],\n\t\"ten thousand thirty four\": [\"mille trente quatre\", \"mille trente-quatre\"],\n\t\"ten three four\": [\"dix trois quatre\"],\n\t\"thing\": [\"chose\", \"la chose\"],\n\t\"time\": [\"le temps\", \"temps\"],\n\t\"trickster\": [\"farceur\", \"filou\", \"fripon\"],\n\t\"true\": [\"v\", \"vrai\"],\n\t\"unintelligible\": [\"incomprehensible\", \"incompréhensible\", \"inintelligible\", \"intraduisible\", \"traduction impossible\"],\n\t\"universal mirror\": [\"miroir universel\"],\n\t\"witness\": [\"le temoin\", \"le témoin\", \"temoin\", \"témoin\"],\n\t\"world\": [\"le monde\", \"monde\"],\n\t\"y\": [\"o\"],\n\t\"yes\": [\"o\", \"oui\"],\n}\n\n\nfunc _fr_alias(reponse: String, saisie: String) -> bool:\n\tfor alias in FR_ALIASES.get(reponse.to_lower(), []):\n\t\tif alias in saisie:\n\t\t\treturn true\n\treturn false\n\n\nfunc _fr_accepte(reponses: Array, saisie: String) -> bool:\n\tif saisie in reponses:\n\t\treturn true\n\tfor reponse in reponses:\n\t\tif saisie in FR_ALIASES.get(String(reponse).to_lower(), []):\n\t\t\treturn true\n\treturn false\n",
		["Scenes/Entities/cuffs.gdc"] = "\n\nconst FR_ALIASES := {\n\t\"announcer\": [\"annonciateur\", \"crieur\", \"heraut\", \"héraut\"],\n\t\"biibiyt\": [\"djjmsvl\"],\n\t\"core\": [\"coeur\", \"cœur\", \"noyau\"],\n\t\"elysium\": [\"élysium\"],\n\t\"false\": [\"f\", \"faux\"],\n\t\"flow\": [\"courant\", \"flot\", \"le flot\"],\n\t\"fly\": [\"envol\", \"vol\", \"voler\"],\n\t\"fool\": [\"fou\", \"idiot\", \"insense\", \"insensé\", \"le fou\"],\n\t\"herald\": [\"heraut\", \"héraut\", \"le heraut\", \"le héraut\"],\n\t\"immortal\": [\"immortalite\", \"immortalité\", \"immortel\", \"immortelle\"],\n\t\"judge\": [\"juge\", \"le juge\"],\n\t\"mad\": [\"dement\", \"dément\", \"fou\", \"le fou\"],\n\t\"no\": [\"non\"],\n\t\"novice\": [\"le novice\", \"novice\"],\n\t\"oblivion\": [\"l'oubli\", \"oubli\"],\n\t\"pattern\": [\"le motif\", \"motif\", \"motifs\", \"schema\", \"schéma\"],\n\t\"patterns\": [\"motif\", \"motifs\", \"regularites\", \"régularités\", \"schemas\", \"schémas\"],\n\t\"planetarium\": [\"planetarium\", \"planétarium\"],\n\t\"star study\": [\"etude des etoiles\", \"observatoire stellaire\", \"étude des étoiles\"],\n\t\"tablet\": [\"la tablette\", \"tablette\"],\n\t\"ten thousand thirty four\": [\"mille trente quatre\", \"mille trente-quatre\"],\n\t\"ten three four\": [\"dix trois quatre\"],\n\t\"thing\": [\"chose\", \"la chose\"],\n\t\"time\": [\"le temps\", \"temps\"],\n\t\"trickster\": [\"farceur\", \"filou\", \"fripon\"],\n\t\"true\": [\"v\", \"vrai\"],\n\t\"unintelligible\": [\"incomprehensible\", \"incompréhensible\", \"inintelligible\", \"intraduisible\", \"traduction impossible\"],\n\t\"universal mirror\": [\"miroir universel\"],\n\t\"witness\": [\"le temoin\", \"le témoin\", \"temoin\", \"témoin\"],\n\t\"world\": [\"le monde\", \"monde\"],\n\t\"y\": [\"o\"],\n\t\"yes\": [\"o\", \"oui\"],\n}\n\n\nfunc _fr_alias(reponse: String, saisie: String) -> bool:\n\tfor alias in FR_ALIASES.get(reponse.to_lower(), []):\n\t\tif alias in saisie:\n\t\t\treturn true\n\treturn false\n\n\nfunc _fr_accepte(reponses: Array, saisie: String) -> bool:\n\tif saisie in reponses:\n\t\treturn true\n\tfor reponse in reponses:\n\t\tif saisie in FR_ALIASES.get(String(reponse).to_lower(), []):\n\t\t\treturn true\n\treturn false\n",
		["Scripts/passage.gdc"] = "\n\n\nconst FR_CLAIRS := {\n\t\"FRIENDWEWILLINITIATETHECORONATIONWITHTHEINTERSECTIONOFSPACE\": \"Mon ami, nous entamerons le couronnement par l'intersection de l'espace.\",\n\t\"BUTFIRSTWEMUSTFINDAWAYTOSTOPTHEMARCHINGOFTIME\": \"Mais il nous faut d'abord trouver le moyen d'arrêter la marche du temps.\",\n\t\"DCDRSOMESAYOLDGODSLINGERINOURPLANEWAITINGFORREALITYTOGIVEWAYTOSOMETHINGNEWTHEYAREMISTAKENFORTHEFLOWOFTHEUNIVERSESTATESTHATALLTHINGSMUSTCHANGEFORTHISISTHEFLUXTHATRULESALLTHINGS\": \"DCDR — Certains disent que d'anciens dieux s'attardent sur notre plan, à attendre que la réalité cède la place à quelque chose de neuf. Ils se trompent : le flot de l'univers veut que toute chose change, car c'est le Flux qui régit toute chose.\",\n\t\"NOTHINGSCANBETRULYDESTROYEDJUSTGIVENDIFFERENTFORMALLTHINGSTHATDONOTEXISTCANBEFOUNDELSEWHEREHIDDENINPATTERNSUNSEENBYUSHAVERESPECTFORALLIDEASREACHINTOTHEUNKNOWNANDDISCOVERWHATISNOTTHERE\": \"Rien ne peut être vraiment détruit, seulement recevoir une autre forme. Toute chose qui n'existe pas se trouve ailleurs, cachée dans des motifs que nous ne voyons pas. Ayez du respect pour toutes les idées. Tendez la main vers l'inconnu, et découvrez ce qui n'est pas là.\",\n\t\"IAMNOTHEREFINDMEINTHEEMPTYSPACESWHEREGODANDMANAREWITHOUTFORMTHEREISNOFORMWHICHIWILLTAKEBEYONDTHEONEINYOURMINDIAMTHERE\": \"Je ne suis pas ici. Trouvez-moi dans les espaces vides, là où le dieu et l'homme sont sans forme. Il n'est aucune forme que je prendrai, hormis celle qui est dans votre esprit. Je suis là.\",\n\t\"ATOPTHETHIRDCIRCLEVIEWXERESTHRICETHENLOOKTOYOURTRUEGOD\": \"Au sommet du troisième cercle, regardez Xeres par trois fois, puis tournez-vous vers votre vrai dieu.\",\n}\n",
	},
}
