-- Généré par tools/gen_strings_lua.py — ne pas éditer à la main.
return {
	["Locations/Constellation/constellation.gdc"] = {
		{"What can be said about him that has not already been said? He is the reason for my existence, how could I critique him?", "Que dire de lui qui n'ait déjà été dit ? Il est la raison de mon existence, comment pourrais-je le critiquer ?"},
		{"You can only get so far in understanding the world through logic. Sometimes you just need to test something out.", "On ne va pas si loin dans la compréhension du monde par la seule logique. Parfois, il faut simplement essayer."},
		{"I do not think he and the Logicians were truly so different. They worked from the same kind of world.", "Je ne crois pas que lui et les Logiciens aient été si différents. Ils partaient du même genre de monde."},
		{"Although Aeons might not be a rigorous concept, they're useful to describe the history of our world.", "Même si les Aeons ne sont pas un concept rigoureux, ils sont utiles pour décrire l'histoire de notre monde."},
		{"A shame what became of their movement. Alas, only the true theories should prevail.", "Dommage, ce qu'est devenu leur mouvement. Hélas, seules les vraies théories devraient l'emporter."},
		{"Will it ever be possible to understand everything there is to know about our world?", "Sera-t-il un jour possible de comprendre tout ce qu'il y a à savoir de notre monde ?"},
		{"I do wonder if the Logicians would have also taken flight, given the opportunity.", "Je me demande si les Logiciens auraient eux aussi pris leur envol, s'ils en avaient eu l'occasion."},
		{"Our technology has improved greatly. Maybe one day might truly go beyond Umai.", "Notre technologie a beaucoup progressé. Peut-être qu'un jour, on ira vraiment au-delà d'Umai."},
		{"With every day that passes, we get closer to truly understanding this world.", "Chaque jour qui passe nous rapproche d'une véritable compréhension de ce monde."},
		{"They were awfully silent about the deities, weren't they? I think they knew.", "Ils sont restés terriblement silencieux sur les divinités, non ? Je crois qu'ils savaient."},
		{"I must admit, I am a little jealous of your ability to explore this world.", "Je dois l'admettre, je suis un peu jalouse de ta capacité à explorer ce monde."},
		{"I was supposed to be his final resting place. What ever happened to him?", "J'étais censée être sa dernière demeure. Que lui est-il donc arrivé ?"},
		{"I imagine I will be here a while. The Fourth Aeon won't be anytime soon.", "J'imagine que je serai là un bon moment. Le Quatrième Aeon n'est pas pour tout de suite."},
		{"Odd how their god of trickery is also their god of execution, isn't it?", "Curieux que leur dieu de la ruse soit aussi leur dieu de l'exécution, non ?"},
		{"Sometimes I wish the deities were real. What would they talk about?", "Parfois, j'aimerais que les divinités soient réelles. De quoi parleraient-elles ?"},
		{"Say what one will, but the Aeon of Logicians is far beyond us now.", "Qu'on en dise ce qu'on veut, l'Aeon des Logiciens est loin derrière nous."},
		{"The Elysium Rocket was bad enough. Best not to shoot near the sun.", "La fusée Elysium était déjà bien assez grave. Mieux vaut ne pas tirer près du soleil."},
		{"Our accomplishments will leave indelible marks through the Aeons.", "Nos accomplissements laisseront des marques indélébiles à travers les Aeons."},
		{"Flight is much harder to master than hovering. I should know.", "Le vol est bien plus dur à maîtriser que la sustentation. Je suis bien placée pour le savoir."},
		{"The Third Aeon. What a fascinating time to live in, no?", "Le Troisième Aeon. Quelle époque fascinante, non ?"},
		{"That's a sign I will always associate with evil.", "C'est un signe que j'associerai toujours au mal."},
		{"It would be nice to travel and see the world.", "Ce serait agréable de voyager et de voir le monde."},
		{"Do the Aeons flow faster on other worlds?", "Les Aeons s'écoulent-ils plus vite sur d'autres mondes ?"},
		{"Was some technology ever lost to time?", "Des technologies se sont-elles perdues avec le temps ?"},
		{"Project Clay could change the world.", "Project Clay pourrait changer le monde."},
		{"My secret muse and interest.", "Ma muse et mon obsession secrètes."},
		{"Do you think I am conscious?", "Me crois-tu consciente ?"},
		{"They condemned him.", "Ils l'ont condamné."},
	},
	["Scenes/Boat/radar.gdc"] = {
		{"Loading [%s]", "Chargement [%s]"},
	},
	["Scenes/Entities/cuffs.gdc"] = {
		{"It is not yet time.", "Ce n'est pas encore le moment."},
	},
	["Scenes/Fishing/fish_caught_screen.gdc"] = {
		{"Best Size: %s\\nBest Weight: %s", "Meilleure taille : %s\\nMeilleur poids : %s"},
		{"Size: %s | Weight: %s", "Taille : %s | Poids : %s"},
		{"Count: %s", "Nombre : %s"},
	},
	["Scenes/Fishing/fish_data.gdc"] = {
		{"Floats near the surface and is terribly common. It is not uncommon to have piles of discarded rotters after a fishing trip.", "Flotte près de la surface, et terriblement commun. Il n'est pas rare de se retrouver avec des tas de rotters mis au rebut après une partie de pêche."},
		{"Said to lurk in only the deepest of depths. Many followers of Atrae place great reverence in these ancient creatures.", "On dit qu'ils ne rôdent que dans les plus grandes profondeurs. Beaucoup de fidèles d'Atrae vouent une grande révérence à ces créatures anciennes."},
		{"A rare predator that keeps to select waters. The body plan is unusual, and it has no known relatives.", "Un prédateur rare, cantonné à certaines eaux. Son plan corporel est inhabituel, et on ne lui connaît aucun parent."},
		{"They are known to be the Announcer. Their first sighting shall bring ruin to all left to see it.", "On les connaît comme l'Annonciateur (Announcer). Leur première apparition apportera la ruine à tous ceux qui resteront pour la voir."},
		{"Discovered only recently, they are the Core, the thing that all anchor themselves to.", "Découverts depuis peu, ils sont le Noyau (Core), la chose à laquelle tous s'amarrent."},
		{"They are called the Judge, for their fate is to determine the fate of the world.", "On les appelle le Juge (Judge), car leur destin est de déterminer le destin du monde."},
		{"They are called Mad, not after themself, but after what they cause in others.", "On les appelle le Dément (Mad), non d'après eux-mêmes, mais d'après ce qu'ils causent chez les autres."},
		{"Sometimes also known as a Tomfish. Regardless of the name, always a good boy.", "Parfois aussi appelé Tomfish. Quel que soit le nom, toujours un bon chien."},
		{"A rare and rather large creature. Considered an ill omen by many.", "Une créature rare et plutôt grande. Beaucoup y voient un mauvais présage."},
		{"A strange creature of the depths. It appears to move in bursts.", "Une créature étrange des profondeurs. Elle semble se déplacer par à-coups."},
		{"Common though often hard to spot due to their dark coloration.", "Commun, mais souvent difficile à repérer à cause de sa coloration sombre."},
		{"A plentiful and cute creature, often kept for recreation.", "Une créature abondante et mignonne, souvent gardée pour l'agrément."},
		{"As the Witness, their job is not to act, but to watch.", "En tant que Témoin (Witness), leur tâche n'est pas d'agir, mais de regarder."},
		{"They are the Fool who will sleep on their last day.", "Ils sont le Fou (Fool) qui dormira en son dernier jour."},
		{"They are the Trickster who profits off of chaos.", "Ils sont le Trompeur (Trickster) qui tire profit du chaos."},
		{"They are three, yet somehow one with Time.", "Ils sont trois, et pourtant, d'une manière ou d'une autre, un avec le Temps (Time)."},
		{"They are the Pattern that all belongs to.", "Ils sont le Motif (Pattern) auquel tout appartient."},
		{"They are the Oblivion that comes for all.", "Ils sont le Néant (Oblivion) qui vient pour tous."},
		{"They are the Thing that cannot be found.", "Ils sont la Chose (Thing) qui ne peut être trouvée."},
		{"They are the Herald of what is to come.", "Ils sont le Héraut (Herald) de ce qui vient."},
		{"The Novice is stronger with tools.", "Le Novice est plus fort avec des outils."},
		{"They are the ground for the World.", "Ils sont le socle du Monde (World)."},
		{"They are the Flow of all things.", "Ils sont le Flot (Flow) de toutes choses."},
		{"They Fly, despite all odds.", "Ils Volent (Fly), contre toute attente."},
	},
	["Scripts/chime.gdc"] = {
		{"Scale: %s\\nPitch: %0.2f\\nGarble: %0.2f\\nHigh: %s\\n", "Gamme : %s\\nHauteur : %0.2f\\nBrouillage : %0.2f\\nAigu : %s\\n"},
	},
	["Scripts/fish_scanner.gdc"] = {
		{"No fish detected nearby.", "Aucun poisson détecté à proximité."},
		{"Fish detected:\\n", "Poisson détecté :\\n"},
		{"Loading [%s]", "Chargement [%s]"},
	},
	["Scripts/journal.gdc"] = {
		{"%s/%s Found", "%s/%s trouvés"},
		{"By %s", "Par %s"},
	},
	["Scripts/loading_screen.gdc"] = {
		{"Abstractists believe in everything that can be imagined. These things always exist, but the way they appear is temporary. They honor Xeres as a symbol of their movement.", "Les Abstractistes croient en tout ce qui peut être imaginé. Ces choses existent toujours, mais leur manière d'apparaître est temporaire. Ils honorent Xeres comme symbole de leur mouvement."},
		{"Idealists believe that there is an infinite number of ideas that make up our world. The world we live in is a set of those ideas. They worship all deities.", "Les Idéalistes croient qu'il existe un nombre infini d'idées qui composent notre monde. Le monde où nous vivons est un ensemble de ces idées. Ils vénèrent toutes les divinités."},
		{"Some argue that true death only happens when we are never thought of again. It is no wonder that we seek to remove all evidence of our enemies in war.", "Certains soutiennent que la vraie mort n'arrive que lorsque plus personne ne pense à nous. Rien d'étonnant à ce que nous cherchions à effacer toute trace de nos ennemis en temps de guerre."},
		{"It is not unusual to stare at the stars and dream about what worlds they might be hiding from us. Perhaps one day we will find a way to visit them.", "Il n'est pas rare de fixer les étoiles en rêvant aux mondes qu'elles pourraient nous cacher. Peut-être trouverons-nous un jour le moyen de les visiter."},
		{"Logicians believe that the root of the world is logic. They argue that anything that is illogical must not exist. Most Logicians worship Cora.", "Les Logiciens croient que la racine du monde est la logique. Ils soutiennent que tout ce qui est illogique ne peut pas exister. La plupart des Logiciens vénèrent Cora."},
		{"Realists believe that matter is the only thing that exists. If one has mastery over matter, they have mastery over reality.", "Les Réalistes croient que la matière est la seule chose qui existe. Qui a la maîtrise de la matière a la maîtrise de la réalité."},
		{"They say that the planets are the deities in their physical form. Only recently has this become controversial.", "On dit que les planètes sont les divinités sous leur forme physique. Ce n'est que récemment que cela est devenu controversé."},
		{"Some esoteric groups dive deep into the lore of a single deity. Their aims are often extreme and obscure.", "Certains groupes ésotériques s'enfoncent dans le savoir d'une seule divinité. Leurs buts sont souvent extrêmes et obscurs."},
		{"A wide variety of oceanic life can be found across the planet. Their origins are unclear, at best.", "Une grande variété de vie océanique se rencontre à travers la planète. Ses origines sont floues, au mieux."},
		{"As long as we have been around to ask, we have wondered what the true nature of the world is.", "Depuis que nous sommes là pour poser la question, nous nous demandons quelle est la vraie nature du monde."},
		{"Does the world have an end? Some believe so. Many say otherwise. More claim there are many.", "Le monde a-t-il une fin ? Certains le croient. Beaucoup disent le contraire. D'autres encore affirment qu'il y en a plusieurs."},
	},
	["Scripts/location_manager.gdc"] = {
		{"Added %s to journal.", "Ajout de %s au journal."},
		{"Notes on %s updated.", "Notes sur %s mises à jour."},
	},
	["Scripts/locations.gdc"] = {
		{"An installation for some kind of rocket or missile launches. There's a few rockets held up in the air, but there doesn't seem to be a path to them.", "Une installation pour des lancements de fusées ou de missiles. Quelques fusées sont maintenues en l'air, mais aucun chemin ne semble y mener."},
		{"A monument of some kind coated with a mirrored finish. Fractal step shapes lead the way upwards. A large, multicolor cube spins overhead.", "Une sorte de monument recouvert d'un fini miroir. Des marches fractales indiquent la montée. Un grand cube multicolore tourne au-dessus."},
		{"The second floor is smaller than the first. On the walls there are a variety of lights. There seems to be an opening to the sky.", "Le deuxième étage est plus petit que le premier. Sur les murs, toutes sortes de lumières. Une ouverture semble donner sur le ciel."},
		{"In the center there's a hexagonal chamber with a spike on the top. The spike seems to be made of the same material as the ocean.", "Au centre, une chambre hexagonale surmontée d'une pointe. La pointe semble faite de la même matière que l'océan."},
		{"There's some wreckage floating in the sea. It appears to be part of a rocket, bearing the word \\\"Elysium\\\" on the side. ", "Des débris flottent sur la mer. On dirait une partie de fusée, portant le mot « Elysium » sur le flanc. "},
		{"A cloud of erratically moving objects in the air. They seem to be attracted to an odd formation in the Mirrored Sea.", "Un nuage d'objets aux mouvements erratiques dans l'air. Ils semblent attirés par une formation étrange dans la Mirrored Sea."},
		{"A large, hexagonal structure. There are six different entrances, each leading to the same central area.", "Une grande structure hexagonale. Six entrées différentes, toutes menant à la même aire centrale."},
		{"A platform with a cloud of still objects hanging in the air. There is an array floating symbols.", "Une plateforme, avec un nuage d'objets immobiles suspendus dans l'air. Un ensemble de symboles flotte."},
		{"Getting all the lights to turn green causes the center of the room to glow. There's a lift up.", "Faire passer toutes les lumières au vert fait luire le centre de la salle. Un ascenseur monte."},
		{"Naming the person who left notes of worship at the deity causes a light to glow in the room.", "Nommer la personne qui a laissé des notes de culte auprès de la divinité allume une lumière dans la pièce."},
		{"Throughout the plaza there's a few different buttons. When pressed, there's a humming noise.", "Quelques boutons différents sont répartis sur la place. Une fois pressés, un bourdonnement se fait entendre."},
		{"A dilapidated metal structure. If there was an original purpose, it is hard to make out now.", "Une structure métallique délabrée. S'il y avait une fonction d'origine, elle est difficile à discerner aujourd'hui."},
		{"A lonely island adrift in the Mirrored Sea. It seems like a good place to rest and think.", "Une île solitaire à la dérive dans la Mirrored Sea. L'endroit paraît bon pour se reposer et réfléchir."},
		{"Entering the correct code into a terminal powers the system. The objects move overhead.", "Saisir le bon code dans un terminal alimente le système. Les objets se mettent en mouvement au-dessus."},
		{"A large dome with a telescope poking out. It seems to trace various objects in the sky.", "Un grand dôme d'où dépasse un télescope. Il semble suivre divers objets dans le ciel."},
		{"There's pillars with no top surrounding a central building with outward-facing rooms.", "Des piliers sans sommet entourent un bâtiment central aux pièces tournées vers l'extérieur."},
		{"There's only one entrance from the outer ring to the inner structure. It is locked.", "Une seule entrée relie l'anneau extérieur à la structure intérieure. Elle est verrouillée."},
		{"When the cube is perfectly aligned, a there's a humming sound inside the temple.", "Quand le cube est parfaitement aligné, un bourdonnement se fait entendre dans le temple."},
		{"A pair of two towers with flashing lights. A low droning noise fills the air.", "Deux tours jumelles aux lumières clignotantes. Un ronflement grave emplit l'air."},
		{"There are two doors in the side of the structure, but one of them is locked.", "Deux portes s'ouvrent dans le flanc de la structure, mais l'une d'elles est verrouillée."},
		{"There's four chambers inside, each dedicated to exploring a different idea.", "Quatre chambres à l'intérieur, chacune consacrée à l'exploration d'une idée différente."},
		{"A lab with locked gates. I need some kind of code to enter at the terminal.", "Un labo aux grilles verrouillées. Il me faut une sorte de code à saisir au terminal."},
		{"There seems to be a desk and a wall of spaces. It doesn't feel quite right.", "Il semble y avoir un comptoir et un mur de casiers. Quelque chose ne va pas."},
		{"A monumental structure with a single outcrop that seems to be an entrance.", "Une structure monumentale, avec une seule saillie qui semble faire office d'entrée."},
		{"Interacting with the central dial causes something interesting to happen.", "Manipuler le cadran central déclenche quelque chose d'intéressant."},
		{"There's a few raised platforms near the center. They seem to be moveable.", "Quelques plateformes surélevées près du centre. Elles semblent déplaçables."},
		{"A large pedestal of some kind, with three spires emerging from the base.", "Une sorte de grand piédestal, avec trois flèches qui émergent de la base."},
		{"A partially submersed object. Parts are barely visible above the waves.", "Un objet partiellement submergé. Des morceaux affleurent à peine au-dessus des vagues."},
		{"I feel a sense of dread here, as if I was not meant to step foot here.", "Un effroi me prend ici, comme si je n'étais pas censé y poser le pied."},
		{"The inside is filled with almost endless racks and aisles of servers. ", "L'intérieur est rempli de baies et d'allées de serveurs presque sans fin. "},
		{"Pressing pairs of symbols somehow produces a response from the system.", "Appuyer sur des paires de symboles produit, d'une manière ou d'une autre, une réponse du système."},
		{"There's a central column with a door in it. It appears to be locked. ", "Une colonne centrale percée d'une porte. Elle semble verrouillée. "},
		{"Some kind of enclosed space with a gate. I need a sequence to get in.", "Une sorte d'espace clos avec une grille. Il me faut une séquence pour entrer."},
		{"It seems there was once museum exhibits here, but most are worn away.", "Il semble y avoir eu ici des vitrines de musée, mais la plupart sont effacées."},
		{"There's a floating torus accompanied by a moving light in the center.", "Un tore flotte au centre, accompagné d'une lumière mobile."},
		{"When the humming noise is tuned right, the door in the center opens.", "Quand le bourdonnement est bien accordé, la porte du centre s'ouvre."},
		{"There's a terminal onboard. It looks similar to the one on the ship.", "Un terminal à bord. Il ressemble à celui du navire."},
		{"There's lights that face the center. Some are off, and some are on.", "Des lumières font face au centre. Certaines sont éteintes, d'autres allumées."},
		{"I can tell that this building might end me in a way I cannot undo.", "Je sens que ce bâtiment pourrait m'anéantir d'une façon irréversible."},
		{"A high-power telescope that seems to automatically track a target.", "Un télescope de forte puissance qui semble suivre une cible automatiquement."},
		{"A large installation in the sea with a radar dish floating nearby.", "Une grande installation en mer, avec une antenne radar qui flotte non loin."},
		{"There's a small floating cube in the sky at the top of the lift. ", "Un petit cube flotte dans le ciel, en haut de l'ascenseur. "},
		{"The dish seems to always point to the planet Parabol in the sky.", "L'antenne semble toujours pointer vers la planète Parabol dans le ciel."},
		{"In the center there appears to be a window to a different world.", "Au centre, ce qui semble être une fenêtre sur un autre monde."},
		{"Along the sides are circular platforms with engravings on them.", "Sur les flancs, des plateformes circulaires portent des gravures."},
		{"A large, low landmass. Strange sparks dance in the air around.", "Une masse de terre vaste et basse. D'étranges étincelles dansent dans l'air alentour."},
		{"The base is a large radial platform with marks etched into it.", "La base est une vaste plateforme radiale gravée de marques."},
		{"A large closed off silo is partially buried beneath the waves.", "Un grand silo condamné est à demi enfoui sous les vagues."},
		{"A large structure with an indescribable surface in the center.", "Une grande structure, avec en son centre une surface indescriptible."},
		{"Overlooking the ocean there's a tablet with a list of crimes.", "Face à l'océan, une tablette porte une liste de crimes."},
		{"A platform with a strange surface and islands floating above.", "Une plateforme à la surface étrange, avec des îles flottant au-dessus."},
		{"There's the form of a building here, but it seems compressed.", "La forme d'un bâtiment est là, mais elle semble comprimée."},
		{"A grid of solar panels. It is unclear if they still function.", "Une grille de panneaux solaires. Difficile de dire s'ils fonctionnent encore."},
		{"At the top there is some kind of terminal and a few buttons.", "Au sommet, une sorte de terminal et quelques boutons."},
		{"A large hall of some kind. There's a ramp leading to a gate.", "Une sorte de grande halle. Une rampe mène à une grille."},
		{"Entering the sequence drops the door, revealing a Hypercube.", "Saisir la séquence abaisse la porte et révèle un Hypercube."},
		{"There's a Golden Frame at the peak. The purpose is unclear.", "Un Golden Frame au sommet. Sa fonction reste obscure."},
		{"The gates seem impenetrable, but perhaps there is a way in.", "Les grilles semblent impénétrables, mais il y a peut-être un moyen d'entrer."},
		{"There's a building nearby that moves whenever I look away.", "Un bâtiment se déplace non loin, chaque fois que je détourne les yeux."},
		{"An array of radar dishes connecting to a central platform.", "Un réseau d'antennes radar reliées à une plateforme centrale."},
		{"The inside is filled with stars and the classical planets.", "L'intérieur est rempli d'étoiles et des planètes classiques."},
		{"The ocean here seems to be solid, forming a cratered hill.", "L'océan paraît solide ici, formant une colline criblée de cratères."},
		{"There seems to be a sculpture of some kind in the center.", "Une sculpture, semble-t-il, se dresse au centre."},
		{"A tall, nondescript tower. One side is open to the world.", "Une haute tour quelconque. Un côté est ouvert sur le monde."},
		{"Getting the right combination causes a lift to activate.", "La bonne combinaison actionne un ascenseur."},
		{"Getting them both to align causes a Corba to drop down.", "Les aligner tous les deux fait descendre un Corba."},
		{"There are scattered obelisks and ruins on the surface.", "Des obélisques et des ruines parsèment la surface."},
		{"A great monument of the Logicians to their deity Cora.", "Un grand monument des Logiciens à leur divinité Cora."},
		{"Correctly identifying each shadow opens a new chamber.", "Identifier correctement chaque ombre ouvre une nouvelle chambre."},
		{"Inputting the password in a hidden space does nothing.", "Saisir le mot de passe dans un espace caché ne donne rien."},
		{"At the base there are walls with buttons and symbols.", "À la base, des murs couverts de boutons et de symboles."},
		{"There are shadows cast by objects that are not there.", "Des ombres sont projetées par des objets qui ne sont pas là."},
		{"Touching the stone makes the columns raise and lower.", "Toucher la pierre fait monter et descendre les colonnes."},
		{"A tall tower with a staircase leading up to the base.", "Une haute tour, un escalier monte jusqu'à sa base."},
		{"There's a space for a deity that seems to be closed.", "Un emplacement de divinité semble condamné."},
		{"There's a unattached radar dish floating in the sea.", "Une antenne radar détachée flotte sur la mer."},
		{"A large fuselage of a rocket floating in the ocean.", "Un grand fuselage de fusée qui flotte sur l'océan."},
		{"Tracing the right word onto one causes an odd hum.", "Tracer le bon mot sur l'un d'eux provoque un bourdonnement étrange."},
		{"A massive structure of dubious purpose and origin.", "Une structure massive, à la fonction et à l'origine douteuses."},
		{"A large installation in the sea with a radar dish.", "Une grande installation en mer, avec une antenne radar."},
		{"A large crystal surrounded by a bridge structure.", "Un grand cristal entouré d'une structure de passerelles."},
		{"There's secret compartments underneath the Chors.", "Des compartiments secrets se cachent sous les Chors."},
		{"Some spots seem to have markings added onto them.", "Certains emplacements semblent avoir reçu des marques."},
		{"A large platform, ideal for sturdy construction.", "Une grande plateforme, idéale pour une construction solide."},
		{"There's a yellow crescent that sways in the air.", "Un croissant jaune oscille dans l'air."},
		{"There's a transcendental pattern on a platform.", "Un motif transcendantal sur une plateforme."},
		{"A radial structure with pillars surrounding it.", "Une structure radiale entourée de piliers."},
		{"A structure that seems to be a kind of museum. ", "Une structure qui semble être une sorte de musée. "},
		{"A tall, dark tower with a staircase leading up.", "Une haute tour sombre, avec un escalier qui monte."},
		{"A large structure built on a tall foundation. ", "Une grande structure bâtie sur de hautes fondations. "},
		{"A radial structure with a large chamber above.", "Une structure radiale surmontée d'une grande chambre."},
		{"There's an odd arrangement of hallways inside.", "À l'intérieur, un agencement de couloirs étrange."},
		{"A large installation concerning the Parallels.", "Une grande installation consacrée aux Parallels."},
		{"There's a large sundial and two sealed vaults.", "Un grand cadran solaire et deux caveaux scellés."},
		{"A tall telescope that points directly upwards.", "Un grand télescope pointé droit vers le haut."},
		{"An odd space with liquid suspended in the air.", "Un espace singulier, avec du liquide en suspension dans l'air."},
		{"A large maze, with walls too high to see over.", "Un grand labyrinthe, aux murs trop hauts pour voir par-dessus."},
		{"There's a small room with a table and chairs.", "Une petite pièce avec une table et des chaises."},
		{"Entering the startup password opens the door.", "Saisir le mot de passe de démarrage ouvre la porte."},
		{"There's a terminal inside labeled Station 50.", "À l'intérieur, un terminal marqué Station 50."},
		{"Appears to be an arch that crumbled and fell.", "On dirait une arche qui s'est effritée et effondrée."},
		{"At the top is a small study with a telescope.", "En haut, un petit cabinet d'étude avec un télescope."},
		{"Deep inside there is something I cannot see.", "Tout au fond, quelque chose que je n'arrive pas à voir."},
		{"There's a drumbeat sound echoing throughout.", "Un battement de tambour résonne partout."},
		{"There's an invisible pathway up to a portal.", "Un chemin invisible monte jusqu'à un portail."},
		{"There's a subtle current of uneasiness here.", "Un courant de malaise passe ici, discret."},
		{"A small shrine with a strange object within.", "Un petit sanctuaire abritant un objet étrange."},
		{"A nondescript island with a structure on it.", "Une île quelconque, avec une structure dessus."},
		{"Each room seems to be dedicated to a deity.", "Chaque pièce semble dédiée à une divinité."},
		{"When the drum beats faster, the door opens.", "Quand le tambour bat plus vite, la porte s'ouvre."},
		{"When I focus, I find myself on the islands.", "Quand je me concentre, je me retrouve sur les îles."},
		{"A long slope leading to a central platform.", "Une longue pente menant à une plateforme centrale."},
		{"A platform with a view of the Golden Idol.", "Une plateforme avec vue sur le Golden Idol."},
		{"There's what seems to be a control center.", "Ce qui ressemble à un centre de contrôle."},
		{"Staggered columns protruding from the sea.", "Des colonnes décalées émergent de la mer."},
		{"A tall tower-shrine leading to a pedestal.", "Une haute tour-sanctuaire menant à un piédestal."},
		{"A sprawling structure with an outer ring.", "Une structure tentaculaire ceinte d'un anneau extérieur."},
		{"Some kind of sculpture made of crescents.", "Une sorte de sculpture faite de croissants."},
		{"In the center there is a busy lab space.", "Au centre, un espace de laboratoire en pleine activité."},
		{"There's an interface of some kind on it.", "Une sorte d'interface est fixée dessus."},
		{"A tall structure with a hum in the air.", "Une haute structure, un bourdonnement dans l'air."},
		{"The air here feels heavier than normal.", "L'air paraît ici plus lourd que la normale."},
		{"A large platform arranged with benches.", "Une grande plateforme aménagée de bancs."},
		{"A large suspended dome above the ocean.", "Un grand dôme suspendu au-dessus de l'océan."},
		{"A great spire made of shimmering gold.", "Une grande flèche d'or scintillant."},
		{"There's a burning altar in the center.", "Un autel en flammes se dresse au centre."},
		{"Some kind of temple with many columns.", "Une sorte de temple aux nombreuses colonnes."},
		{"An archive dedicated to unique ideas.", "Une archive dédiée aux idées singulières."},
		{"A temple with various viewing spaces.", "Un temple aux multiples espaces d'observation."},
		{"A massive dome with darkness within.", "Un dôme massif, et de l'obscurité à l'intérieur."},
		{"There's two terminals in the center.", "Deux terminaux au centre."},
		{"There's nothing inside the exhibits.", "Les vitrines sont vides."},
		{"A bright cloud billows out the top.", "Un nuage éclatant s'échappe du sommet."},
		{"A tower with locked, gated floors.", "Une tour aux étages verrouillés par des grilles."},
		{"The object within is most curious.", "L'objet qu'elle abrite est des plus curieux."},
		{"It seems particularly in disarray.", "Elle paraît particulièrement en désordre."},
		{"The house is bigger on the inside.", "La maison est plus grande à l'intérieur."},
		{"Coordinates downloaded from file.", "Coordonnées téléchargées depuis un fichier."},
		{"A tall tower enclosing an object.", "Une haute tour qui enferme un objet."},
		{"A lonesome rock against the sea.", "Un rocher solitaire face à la mer."},
		{"An engraved stone on a pedestal.", "Une pierre gravée sur un piédestal."},
		{"Strange forms dance in the air.", "D'étranges formes dansent dans l'air."},
		{"A platform with nothing on it.", "Une plateforme, et rien dessus."},
		{"There's nothing in the center.", "Il n'y a rien au centre."},
		{"A small building in the ocean.", "Un petit bâtiment sur l'océan."},
		{"It seems largely unmaintained.", "Elle semble largement laissée à l'abandon."},
		{"Meditating brings me inside.", "Méditer me fait entrer."},
		{"It connects to True South.", "Elle est reliée à True South."},
		{"It connects to True North.", "Elle est reliée à True North."},
		{"It connects to True West.", "Elle est reliée à True West."},
		{"It connects to True East.", "Elle est reliée à True East."},
		{"A lonesome island at sea.", "Une île solitaire en pleine mer."},
		{"A large grid of towers.", "Une vaste grille de tours."},
		{"A colossal mountain.", "Une montagne colossale."},
		{"An empty platform.", "Une plateforme vide."},
		{"There indeed is.", "Il y en a un, en effet."},
	},
	["Scripts/main_menu.gdc"] = {
		{"Discovered all locations.", "Tous les lieux découverts."},
		{"Complete the tutorial!", "Terminez le tutoriel !"},
		{"[Start Game]", "[Jouer]"},
		{"Prerelease ", "Préversion "},
		{"Release ", "Version "},
		{"Demo ", "Démo "},
		{"Done.", "Terminé."},
	},
	["Scripts/passage.gdc"] = {
		{"Not yet discovered...", "Pas encore découvert..."},
	},
	["Scripts/pause_screen.gdc"] = {
		{"Only Journal is saved in the demo!", "Seul le journal est sauvegardé dans la démo !"},
		{"Save Game", "Sauvegarder"},
		{"Saved!", "Sauvegardé !"},
	},
	["Scripts/player.gdc"] = {
		{"Local Energy: %s", "Énergie locale : %s"},
		{"Particulates: %s", "Particules : %s"},
		{"RG-Shift: %s", "Décalage RV : %s"},
		{"Clarity: %s", "Clarté : %s"},
	},
	["Scripts/terminal_manager.gdc"] = {
		{"TerminalOS 1.2 - Available commands: unlock, lock, download, key. Other commands may not be finished.", "TerminalOS 1.2 - Commandes disponibles : unlock, lock, download, key. D'autres commandes sont peut-être inachevées."},
		{"Invalid argument count. Usage: unlock [target] [key]", "Nombre d'arguments invalide. Utilisation : unlock [cible] [clé]"},
		{"No communication found between host %s and host %s.", "Aucune communication trouvée entre l'hôte %s et l'hôte %s."},
		{"Command [%s] not recognized.", "Commande [%s] non reconnue."},
		{"Invalid key for target.", "Clé invalide pour cette cible."},
		{"No terminal unlocked!", "Aucun terminal déverrouillé !"},
		{"Cannot unlock self.", "Impossible de se déverrouiller soi-même."},
		{"Target not found.", "Cible introuvable."},
		{"Unlocked host %s.", "Hôte %s déverrouillé."},
	},
	["Scripts/text_manager.gdc"] = {
		{"When new discoveries are made, they will be added here to your journal.", "Quand de nouvelles découvertes seront faites, elles seront ajoutées ici, dans votre journal."},
		{"You can search and favorite your discoveries for easy recall.", "Vous pouvez chercher vos découvertes et les mettre en favoris pour les retrouver facilement."},
		{"%s %s already in journal.", "%s %s déjà dans le journal."},
		{"%s %s added to journal.", "Ajout de %s %s au journal."},
		{"%s added to journal.", "Ajout de %s au journal."},
	},
}
